# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IBM Public Cloud Object Storage Documentation
email: nicholas.lange@ibm.com
description: Pre-release documentation for IBM Cloud Object Storage closed beta
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "http://ibm-public-cos.github.io" # the base hostname & protocol for your site
twitter_username: nglange
github_username:  nglange



# Build settings
permalink: /:title
top-level: /:top-level

kramdown:
  input: GFM
  syntax_highlighter: rouge


#variables
author: /:author

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      dateAdded: "August 18, 2016"
      author: "IBM Cloud Object Storage"
      job-title:

sass:
    style: compressed

collections:
  gettingstarted:
    output: true
    permalink: /beta/gettingstarted/:path/
  api:
    output: true
    permalink: /beta/api/:path/
